# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54e8481cf4fa6d06661fdab328c80cf6db3fff0f147494f3d5458dc56031087f8eded7bd329110956533c668823b1cf4b660c649fecc124097da98efacb09a27

test:
  secret_key_base: 9ac6a8fccd25c0e8b8e248163703136f07660c7720c92e3975090f83818b0a81d70e07a5e5b008ebdf7b8e6dedc6a96cb67be9c980ed6a225caeff5046c9a561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
